### ISSUE TITLE
NPC collision

### ISSUE THREAD

**Issue by Coffee4cr** [miicck/dont-get-lost#10] opened 2023-02-06 17:56 UTC
NPC's don't collide with each other, but collides with the player. I don't know if there's a reason for it, but removing the collision with the player would remove tons of annoyance of getting pushed around.

**Comment by Coffee4cr** [comment] 2023-02-06 18:50
I've been looking at the code, and maybe It's just the trader that's colliding? I do know there was something pushing me around when trying to build my walls.

**Comment by Coffee4cr** [comment] 2023-02-07 03:02
Tested it again tonight, NPCs in general body block you (but not themselves)

**Comment by miicck** [comment] 2023-02-12 21:11
Duplicate of: https://github.com/miicck/dont-get-lost/issues/24
Which has been fixed.

**Closed by miicck** 2023-02-12 21:11 UTC
